FROM danxiaonuo/subweb
LABEL maintainer="Satrorn <satrorn@gmail.com>"

ENV VERSION v2022.11

# 拷贝配置文件	
COPY conf/sub-web/.env /sub-web/.env
COPY conf/sub-web/Subconverter.vue /sub-web/src/views/Subconverter.vue