# 利用GitHub Action自动构建多框架的docker镜像
name: 编译镜像(订阅)

# 设置触发条件
on:
# 手动触发工作流
  workflow_dispatch:
    inputs:
      project:
        description: 'project'
        required: true
      # 定时请填写default参数
        default: 'zh'
      tag:
        description: 'tag'
        required: true
      # 定时请填写default参数
        default: 'latest'

# 仓库触发工作流
#  repository_dispatch:

# 编辑文件触发开始编译
# master分支的push操作会触发当前脚本的执行
  push:
    branches: [ master ]
    paths:
      - .github/workflows/build_zh.yml
# main分支的pr操作会触发当前脚本的执行
#  pull_request:
#    branches: [ master ]

# 定时任务,分时日月年,为国际标准时间16点,对应中国时间0点
#  schedule:
#    - cron: '0 16 * * *'

# 点击star时开始任务
#  watch:
#    types: started

 # 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest

    # 运行步骤
    steps:
      # 检出master分支
      - name: 出各个模块代码
        uses: actions/checkout@v3

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 安装 docker buildx
        uses: docker/setup-buildx-action@v2

      - name: 日期版本号
        id: tag
        run: |
          if [[ -n $(cat ${{ github.event.inputs.project }}/Dockerfile | awk '{if($1~"ENV" && $2=="VERSION")print $3}') ]]; then
            VERSION=$(cat ${{ github.event.inputs.project }}/Dockerfile | awk '{if($1~"ENV" && $2=="VERSION")print $3}')
            echo "tag=$VERSION" >> $GITHUB_ENV
          else
            echo "tag=$(date +%Y)$(date +%m)$(date +%d)" >> $GITHUB_ENV
          fi

      - name: 版本分类
        id: prepare
        # IMAGE_NAME ： 镜像名称
        # ALI_ADD ：阿里镜像地址
        # TIME_VERSION ： 日期版本
        # DOCKERHUB_VERSION ： DockerHub 镜像版本
        # TAG_VERSION ： 标签版本 satrorn/XXX:0.0
        # TAG_LATEST ： 最新版本 satrorn/XXX:latest
        # ALI_VERSION ： registry.cn-shenzhen.aliyuncs.com/inc/satrorn/XXX:0.0
        # ALI_LATEST : registry.cn-shenzhen.aliyuncs.com/inc/satrorn/XXX:latest
        # AUTO_UPDATE_TAG : satrorn/XXX:20221111
        # AUTO_UPDATE_ALI : registry.cn-shenzhen.aliyuncs.com/inc/satrorn/XXX:20221111
        run: |
          IMAGE_NAME=${{ github.event.inputs.project }}
          ALI_ADD=registry.cn-shenzhen.aliyuncs.com

          TIME_VERSION=${{ env.tag }}
          DOCKERHUB_VERSION=${{ github.event.inputs.tag }}

          TAG_VERSION="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${DOCKERHUB_VERSION}"
          TAG_LATEST="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:latest"

          ALI_VERSION="${ALI_ADD}/${{ secrets.ALIYUN_NAMESPACES }}/${IMAGE_NAME}:${DOCKERHUB_VERSION}"
          ALI_LATEST="${ALI_ADD}/${{ secrets.ALIYUN_NAMESPACES }}/${IMAGE_NAME}:latest"

          AUTO_UPDATE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${TIME_VERSION}"
          AUTO_UPDATE_ALI="${ALI_ADD}/${{ secrets.ALIYUN_NAMESPACES }}/${IMAGE_NAME}:${TIME_VERSION}"

          echo "time_version=${TIME_VERSION}" >> $GITHUB_OUTPUT
          echo "dockerhub_version=${DOCKERHUB_VERSION}" >> $GITHUB_OUTPUT

          echo "tag_version=${TAG_VERSION}" >> $GITHUB_OUTPUT
          echo "tag_latest=${TAG_LATEST}" >> $GITHUB_OUTPUT

          echo "ali_version=${ALI_VERSION}" >> $GITHUB_OUTPUT
          echo "ali_latest=${ALI_LATEST}" >> $GITHUB_OUTPUT

          echo "auto_update_tag=${AUTO_UPDATE_TAG}" >> $GITHUB_OUTPUT
          echo "auto_update_ali=${AUTO_UPDATE_ALI}" >> $GITHUB_OUTPUT

      # 登录到DOCKERHUB
      - name: 登陆DOCKERHUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 登录到阿里镜像仓库
      - name: 登陆ALIYUN
        run: |
          docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PASSWORD }} registry.cn-shenzhen.aliyuncs.com

      # 构建Amd64和Arm64的镜像
      - name: 构建和推送
        uses: docker/build-push-action@v2
        with:
          context: .
          file: zh/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.prepare.outputs.tag_version }}
            ${{ steps.prepare.outputs.tag_latest }}
            ${{ steps.prepare.outputs.ali_version }}
            ${{ steps.prepare.outputs.ali_latest }}
            ${{ steps.prepare.outputs.auto_update_tag }}
            ${{ steps.prepare.outputs.auto_update_ali }}

      # 同步简介
      - name: README.md
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.project }}
          readme: "${{ github.event.inputs.project }}/README.md"

      # 删除旧的工作流
      - name: Del
        uses: Mattraks/delete-workflow-runs@main
        with:
          repository: ${{ github.repository }}
          retain_days: 1
          # 保留多少个workflow不删除
          keep_minimum_runs: 1
